import { Atom, BookOpen, Calculator, Clock3, FlaskConical, Sigma, Waves } from 'lucide-react';
import type { Chapter, Lesson, Profile, Question, Subject, TestSession, Topic, UserProgress } from '../types';

export const DEMO_USER_ID = 'demo-user';

export const iconMap = {
  Calculator,
  Atom,
  Clock: Clock3,
  Book: BookOpen,
  Flask: FlaskConical,
  Sigma,
  Waves,
};

export const sampleProfile: Profile = {
  id: DEMO_USER_ID,
  full_name: 'Ava Patel',
  email: 'ava@adaptlearn.dev',
  learner_type: 'steady',
  current_level: 'intermediate',
  ability_score: 62,
  created_at: new Date().toISOString(),
};

export const sampleSubjects: Subject[] = [
  {
    id: 'subject-mathematics',
    name: 'Mathematics',
    description: 'Intermediate mathematics with algebra, geometry, trigonometry, calculus, statistics, and number theory.',
    category: 'Intermediate STEM',
    estimated_minutes: 720,
    icon: 'Sigma',
    color: 'cyan',
    chapterCount: 2,
    topicCount: 6,
    difficultyLabel: 'Medium',
  },
  {
    id: 'subject-physics',
    name: 'Physics',
    description: 'Build conceptual strength in mechanics, waves, thermodynamics, electromagnetism, optics, and modern physics.',
    category: 'Intermediate STEM',
    estimated_minutes: 720,
    icon: 'Waves',
    color: 'indigo',
    chapterCount: 2,
    topicCount: 6,
    difficultyLabel: 'Medium',
  },
  {
    id: 'subject-chemistry',
    name: 'Chemistry',
    description: 'Explore atomic structure, bonding, reactions, equilibrium, organic chemistry, and environmental chemistry.',
    category: 'Intermediate STEM',
    estimated_minutes: 720,
    icon: 'Flask',
    color: 'emerald',
    chapterCount: 2,
    topicCount: 6,
    difficultyLabel: 'Medium',
  },
];

export const sampleChapters: Chapter[] = [
  {
    id: 'chapter-math-algebra',
    subject_id: 'subject-mathematics',
    title: 'Algebra Foundations',
    description: 'Expressions, equations, and functions for intermediate problem solving.',
    chapter_number: 1,
    estimated_hours: 12,
    difficulty_level: 'intermediate',
    prerequisites: ['Basic arithmetic'],
    learning_objectives: ['Model relationships', 'Solve equations', 'Interpret function behavior'],
  },
  {
    id: 'chapter-math-geometry',
    subject_id: 'subject-mathematics',
    title: 'Geometry and Trigonometry',
    description: 'Coordinate geometry, triangles, circles, and trigonometric reasoning.',
    chapter_number: 2,
    estimated_hours: 14,
    difficulty_level: 'intermediate',
    prerequisites: ['Algebra Foundations'],
    learning_objectives: ['Visualize shapes', 'Use trigonometric ratios', 'Solve measurement problems'],
  },
  {
    id: 'chapter-physics-mechanics',
    subject_id: 'subject-physics',
    title: 'Mechanics',
    description: 'Motion, forces, energy, and momentum in one connected chapter.',
    chapter_number: 1,
    estimated_hours: 13,
    difficulty_level: 'intermediate',
    prerequisites: ['Basic algebra'],
    learning_objectives: ['Describe motion', 'Apply Newtonian reasoning', 'Conserve energy and momentum'],
  },
  {
    id: 'chapter-physics-fields',
    subject_id: 'subject-physics',
    title: 'Waves, Fields, and Heat',
    description: 'Thermal physics, wave behavior, and introductory electromagnetism.',
    chapter_number: 2,
    estimated_hours: 14,
    difficulty_level: 'intermediate',
    prerequisites: ['Mechanics'],
    learning_objectives: ['Compare heat transfer', 'Analyze waves', 'Interpret electric and magnetic fields'],
  },
  {
    id: 'chapter-chem-atomic',
    subject_id: 'subject-chemistry',
    title: 'Atomic Structure and Bonding',
    description: 'The atomic model, electron arrangement, periodic trends, and chemical bonding.',
    chapter_number: 1,
    estimated_hours: 12,
    difficulty_level: 'intermediate',
    prerequisites: ['Basic science'],
    learning_objectives: ['Describe atoms', 'Use the periodic table', 'Predict bonding patterns'],
  },
  {
    id: 'chapter-chem-reactions',
    subject_id: 'subject-chemistry',
    title: 'Reactions and Chemical Systems',
    description: 'Chemical change, mole relationships, equilibrium, acids, and organic patterns.',
    chapter_number: 2,
    estimated_hours: 15,
    difficulty_level: 'intermediate',
    prerequisites: ['Atomic Structure and Bonding'],
    learning_objectives: ['Balance reactions', 'Reason with moles', 'Predict system behavior'],
  },
];

export const sampleTopics: Topic[] = [
  {
    id: 'topic-linear-equations',
    chapter_id: 'chapter-math-algebra',
    subject_id: 'subject-mathematics',
    title: 'Linear Equations',
    description: 'Solve one-variable linear equations and model situations algebraically.',
    topic_number: 1,
    estimated_minutes: 55,
    difficulty: 2,
    key_concepts: ['Inverse operations', 'Balancing equations', 'Variable isolation'],
    prerequisites: ['Arithmetic operations'],
  },
  {
    id: 'topic-quadratics',
    chapter_id: 'chapter-math-algebra',
    subject_id: 'subject-mathematics',
    title: 'Quadratic Equations',
    description: 'Factor, interpret, and solve quadratic equations in multiple forms.',
    topic_number: 2,
    estimated_minutes: 65,
    difficulty: 3,
    key_concepts: ['Factoring', 'Roots', 'Parabolas'],
    prerequisites: ['Linear Equations'],
  },
  {
    id: 'topic-functions',
    chapter_id: 'chapter-math-algebra',
    subject_id: 'subject-mathematics',
    title: 'Functions and Graphs',
    description: 'Understand input-output rules, graphs, and rates of change.',
    topic_number: 3,
    estimated_minutes: 60,
    difficulty: 3,
    key_concepts: ['Function notation', 'Slope', 'Graph interpretation'],
    prerequisites: ['Linear Equations'],
  },
  {
    id: 'topic-coordinate-geometry',
    chapter_id: 'chapter-math-geometry',
    subject_id: 'subject-mathematics',
    title: 'Coordinate Geometry',
    description: 'Distance, midpoint, gradients, and straight-line geometry.',
    topic_number: 1,
    estimated_minutes: 55,
    difficulty: 3,
    key_concepts: ['Distance formula', 'Midpoint', 'Gradient'],
    prerequisites: ['Functions and Graphs'],
  },
  {
    id: 'topic-triangles',
    chapter_id: 'chapter-math-geometry',
    subject_id: 'subject-mathematics',
    title: 'Triangles and Congruence',
    description: 'Reason about triangle properties, similarity, and congruence.',
    topic_number: 2,
    estimated_minutes: 60,
    difficulty: 3,
    key_concepts: ['Congruence', 'Similarity', 'Angle reasoning'],
    prerequisites: ['Coordinate Geometry'],
  },
  {
    id: 'topic-trigonometry',
    chapter_id: 'chapter-math-geometry',
    subject_id: 'subject-mathematics',
    title: 'Trigonometric Ratios',
    description: 'Use sine, cosine, and tangent to solve right-triangle problems.',
    topic_number: 3,
    estimated_minutes: 70,
    difficulty: 4,
    key_concepts: ['SOHCAHTOA', 'Angle of elevation', 'Right-triangle solving'],
    prerequisites: ['Triangles and Congruence'],
  },
  {
    id: 'topic-kinematics',
    chapter_id: 'chapter-physics-mechanics',
    subject_id: 'subject-physics',
    title: 'Kinematics',
    description: 'Describe motion using displacement, velocity, acceleration, and graphs.',
    topic_number: 1,
    estimated_minutes: 55,
    difficulty: 2,
    key_concepts: ['Velocity', 'Acceleration', 'Motion graphs'],
    prerequisites: ['Basic algebra'],
  },
  {
    id: 'topic-newton-laws',
    chapter_id: 'chapter-physics-mechanics',
    subject_id: 'subject-physics',
    title: 'Newton’s Laws',
    description: 'Connect force, mass, and acceleration in everyday systems.',
    topic_number: 2,
    estimated_minutes: 60,
    difficulty: 3,
    key_concepts: ['Net force', 'Inertia', 'Action-reaction'],
    prerequisites: ['Kinematics'],
  },
  {
    id: 'topic-energy',
    chapter_id: 'chapter-physics-mechanics',
    subject_id: 'subject-physics',
    title: 'Work and Energy',
    description: 'Relate force, work, kinetic energy, and potential energy.',
    topic_number: 3,
    estimated_minutes: 60,
    difficulty: 3,
    key_concepts: ['Work', 'Energy conservation', 'Power'],
    prerequisites: ['Newton’s Laws'],
  },
  {
    id: 'topic-waves',
    chapter_id: 'chapter-physics-fields',
    subject_id: 'subject-physics',
    title: 'Waves and Oscillations',
    description: 'Study wave properties, oscillation, and transfer of energy.',
    topic_number: 1,
    estimated_minutes: 55,
    difficulty: 3,
    key_concepts: ['Amplitude', 'Frequency', 'Wavelength'],
    prerequisites: ['Kinematics'],
  },
  {
    id: 'topic-heat',
    chapter_id: 'chapter-physics-fields',
    subject_id: 'subject-physics',
    title: 'Thermodynamics',
    description: 'Temperature, heat transfer, internal energy, and efficiency.',
    topic_number: 2,
    estimated_minutes: 60,
    difficulty: 3,
    key_concepts: ['Heat transfer', 'Specific heat', 'Efficiency'],
    prerequisites: ['Energy'],
  },
  {
    id: 'topic-electricity',
    chapter_id: 'chapter-physics-fields',
    subject_id: 'subject-physics',
    title: 'Electromagnetism',
    description: 'Charge, electric fields, current, and magnetic effects.',
    topic_number: 3,
    estimated_minutes: 70,
    difficulty: 4,
    key_concepts: ['Current', 'Potential difference', 'Magnetic fields'],
    prerequisites: ['Waves and Oscillations'],
  },
  {
    id: 'topic-atomic-models',
    chapter_id: 'chapter-chem-atomic',
    subject_id: 'subject-chemistry',
    title: 'Atomic Models',
    description: 'Trace the development of atomic theory and particle structure.',
    topic_number: 1,
    estimated_minutes: 50,
    difficulty: 2,
    key_concepts: ['Subatomic particles', 'Atomic number', 'Mass number'],
    prerequisites: ['Basic science'],
  },
  {
    id: 'topic-electron-config',
    chapter_id: 'chapter-chem-atomic',
    subject_id: 'subject-chemistry',
    title: 'Electron Configuration',
    description: 'Arrange electrons in shells and use them to explain reactivity.',
    topic_number: 2,
    estimated_minutes: 55,
    difficulty: 3,
    key_concepts: ['Energy levels', 'Valence electrons', 'Electronic structure'],
    prerequisites: ['Atomic Models'],
  },
  {
    id: 'topic-bonding',
    chapter_id: 'chapter-chem-atomic',
    subject_id: 'subject-chemistry',
    title: 'Chemical Bonding',
    description: 'Ionic, covalent, and metallic bonding with structure-property links.',
    topic_number: 3,
    estimated_minutes: 60,
    difficulty: 3,
    key_concepts: ['Ionic bonding', 'Covalent bonding', 'Metallic bonding'],
    prerequisites: ['Electron Configuration'],
  },
  {
    id: 'topic-reaction-types',
    chapter_id: 'chapter-chem-reactions',
    subject_id: 'subject-chemistry',
    title: 'Reaction Types',
    description: 'Classify and interpret common classes of chemical reactions.',
    topic_number: 1,
    estimated_minutes: 55,
    difficulty: 2,
    key_concepts: ['Synthesis', 'Decomposition', 'Displacement'],
    prerequisites: ['Chemical Bonding'],
  },
  {
    id: 'topic-mole-concept',
    chapter_id: 'chapter-chem-reactions',
    subject_id: 'subject-chemistry',
    title: 'Mole Concept',
    description: 'Count particles, convert mass, and use moles in equations.',
    topic_number: 2,
    estimated_minutes: 65,
    difficulty: 4,
    key_concepts: ['Avogadro constant', 'Molar mass', 'Stoichiometry'],
    prerequisites: ['Reaction Types'],
  },
  {
    id: 'topic-acids-bases',
    chapter_id: 'chapter-chem-reactions',
    subject_id: 'subject-chemistry',
    title: 'Acids, Bases, and pH',
    description: 'Interpret acidity, alkalinity, neutralization, and pH trends.',
    topic_number: 3,
    estimated_minutes: 60,
    difficulty: 3,
    key_concepts: ['pH scale', 'Neutralization', 'Indicators'],
    prerequisites: ['Reaction Types'],
  },
];

function buildLessonContent(topic: Topic, chapterTitle: string) {
  const concepts = topic.key_concepts.join(', ');
  const prerequisite = topic.prerequisites[0] ?? 'foundational prior knowledge';
  return {
    big_idea: `${topic.title} builds a core intermediate understanding inside ${chapterTitle}.`,
    explanation: `Overview:\n${topic.title} is one of the most important building blocks inside ${chapterTitle}. This topic connects directly to ${concepts}, and learners need more than a short definition to really understand it.\n\nWhy it matters:\nWhen students understand ${topic.title.toLowerCase()}, they stop treating questions as isolated tricks and start seeing the underlying structure. That makes problem solving faster, more accurate, and more transferable to harder chapter problems.\n\nCore idea in simple language:\nYou can think of ${topic.title.toLowerCase()} as a system for organizing information. Instead of rushing to an answer, the learner identifies what is known, what must be found, and which relationship connects the two. This is especially important because intermediate students often lose marks not from lack of intelligence, but from weak structure in their reasoning.\n\nHow this topic grows from earlier learning:\nThis topic depends on ${prerequisite}. Earlier knowledge gives the learner the tools, but this chapter pushes them to use those tools with more precision, better interpretation, and more confidence.\n\nWhat strong learners do here:\nStrong learners explain each step, justify why a method works, and compare one method with another. They do not simply memorize outcomes. They can tell when a result is reasonable and when they need to re-check their assumptions.\n\nCommon learner mistakes:\n1. Starting calculations before understanding the question.\n2. Ignoring the meaning of key terms or symbols.\n3. Choosing a method because it looks familiar instead of because it fits.\n4. Forgetting to check whether the final answer is logically consistent.\n\nStudy strategy:\nRead the example slowly, identify the pattern, and then solve one similar problem while explaining each step aloud. That combination of reasoning and reflection is what helps this topic stick.`,
    worked_example: `Worked example framework for ${topic.title}:\n\nStep 1: Read the problem carefully and identify the exact quantity, relationship, or concept being tested.\nStep 2: Underline the information that is given and separate it from what needs to be found.\nStep 3: Match the problem to the right rule, relationship, or representation connected to ${concepts}.\nStep 4: Solve one step at a time and explain why each step is valid.\nStep 5: Compare the result to the original question and check if the answer is realistic.\n\nTeacher-style guidance:\nA good learner does not just say “this is the answer.” A good learner says “this is the answer because this relationship applies, this step follows from the previous one, and the final result matches the conditions of the problem.”\n\nReflection prompt:\nIf you solved the problem a different way, would the structure still make sense? If not, go back and identify the first step where your reasoning changed.`,
    key_skills: topic.key_concepts,
    remember_points: [
      `Anchor on the big idea before calculating or substituting values.`,
      `Use the prerequisite knowledge from ${prerequisite} instead of treating this topic as isolated.`,
      `Check every answer for units, signs, scale, and logical consistency before moving on.`,
    ],
    quick_check: [
      {
        question: `Which idea is most central to ${topic.title}?`,
        options: [topic.key_concepts[0], 'Memorizing without reasoning', 'Skipping examples', 'Guessing from patterns'],
        correct: 0,
      },
      {
        question: `What should you do before the final answer in ${topic.title}?`,
        options: ['Ignore the question', 'Check if the result makes sense', 'Restart the topic', 'Change the formula randomly'],
        correct: 1,
      },
      {
        question: `Which prerequisite supports ${topic.title}?`,
        options: [topic.prerequisites[0] ?? 'Basic foundations', 'No prerequisite is needed', 'Only memorization', 'Only speed'],
        correct: 0,
      },
    ],
  };
}

export const sampleLessons: Lesson[] = sampleTopics.map((topic) => {
  const chapter = sampleChapters.find((item) => item.id === topic.chapter_id)!;
  return {
    id: `lesson-${topic.id}`,
    subject_id: topic.subject_id,
    chapter_id: topic.chapter_id,
    topic_id: topic.id,
    concept_tag: topic.key_concepts[0].toLowerCase().replace(/[^a-z0-9]+/g, '_'),
    title: topic.title,
    difficulty: topic.difficulty,
    version: 1,
    content_json: buildLessonContent(topic, chapter.title),
  };
});

export const sampleQuestions: Question[] = sampleTopics.flatMap((topic) => {
  const baseTag = topic.key_concepts[0].toLowerCase().replace(/[^a-z0-9]+/g, '_');
  return [
    {
      id: `q-${topic.id}-1`,
      topic_id: topic.id,
      chapter_id: topic.chapter_id,
      concept_tag: baseTag,
      question_text: `Which concept is directly associated with ${topic.title}?`,
      options: [topic.key_concepts[0], 'Random guessing', 'No concept applies', 'Only memorization'],
      correct_answer: 0,
      difficulty: Math.max(1, topic.difficulty - 1),
      explanation: `${topic.key_concepts[0]} is one of the anchor concepts for ${topic.title}.`,
      subject_id: topic.subject_id,
    },
    {
      id: `q-${topic.id}-2`,
      topic_id: topic.id,
      chapter_id: topic.chapter_id,
      concept_tag: baseTag,
      question_text: `What is the best strategy when solving a ${topic.title.toLowerCase()} problem?`,
      options: ['Identify the rule, then apply it carefully', 'Skip the setup and guess', 'Memorize the final answer only', 'Ignore the prerequisite ideas'],
      correct_answer: 0,
      difficulty: topic.difficulty,
      explanation: 'Adaptive learning rewards structured reasoning more than speed without understanding.',
      subject_id: topic.subject_id,
    },
    {
      id: `q-${topic.id}-3`,
      topic_id: topic.id,
      chapter_id: topic.chapter_id,
      concept_tag: baseTag,
      question_text: `Why does ${topic.title} belong inside ${sampleChapters.find((chapter) => chapter.id === topic.chapter_id)?.title}?`,
      options: [
        `Because it builds on ${topic.prerequisites[0] ?? 'earlier knowledge'} and supports later topics`,
        'Because the title sounds similar',
        'Because all chapters are identical',
        'Because order never matters',
      ],
      correct_answer: 0,
      difficulty: Math.min(5, topic.difficulty + 1),
      explanation: 'The chapter structure is designed to build understanding in a logical order.',
      subject_id: topic.subject_id,
    },
    {
      id: `q-${topic.id}-4`,
      topic_id: topic.id,
      chapter_id: topic.chapter_id,
      concept_tag: baseTag,
      question_text: `Which mistake is most likely to hurt performance in ${topic.title}?`,
      options: [
        'Skipping the reasoning and jumping straight to an answer',
        `Using ${topic.key_concepts[0]} carefully`,
        'Checking the final result',
        'Connecting the topic to earlier learning',
      ],
      correct_answer: 0,
      difficulty: topic.difficulty,
      explanation: 'Students usually lose marks when they skip structure and reasoning.',
      subject_id: topic.subject_id,
    },
    {
      id: `q-${topic.id}-5`,
      topic_id: topic.id,
      chapter_id: topic.chapter_id,
      concept_tag: baseTag,
      question_text: `What should a strong learner do after solving a ${topic.title.toLowerCase()} question?`,
      options: [
        'Check whether the answer fits the question conditions',
        'Move on without reviewing',
        'Ignore units and assumptions',
        'Memorize the final number only',
      ],
      correct_answer: 0,
      difficulty: Math.min(5, topic.difficulty + 1),
      explanation: 'Verification is part of strong problem solving, not an optional extra step.',
      subject_id: topic.subject_id,
    },
    {
      id: `q-${topic.id}-6`,
      topic_id: topic.id,
      chapter_id: topic.chapter_id,
      concept_tag: baseTag,
      question_text: `Which prerequisite best supports success in ${topic.title}?`,
      options: [
        topic.prerequisites[0] ?? 'Basic foundations',
        'No earlier topic matters',
        'Only speed matters',
        'Only memorizing formulas matters',
      ],
      correct_answer: 0,
      difficulty: Math.max(1, topic.difficulty - 1),
      explanation: 'This topic builds on earlier knowledge, so prerequisites matter.',
      subject_id: topic.subject_id,
    },
  ];
});

export const sampleProgress: UserProgress[] = sampleLessons.map((lesson, index) => ({
  id: `progress-${lesson.id}`,
  user_id: DEMO_USER_ID,
  lesson_id: lesson.id,
  topic_id: lesson.topic_id,
  chapter_id: lesson.chapter_id,
  subject_id: lesson.subject_id,
  status: index === 0 ? 'available' : index < 3 ? 'in_progress' : 'locked',
  mastery_percent: index === 0 ? 68 : index === 1 ? 42 : index === 2 ? 55 : 0,
  last_accessed: index < 3 ? new Date().toISOString() : undefined,
  content_variant: 'default',
}));

export const sampleSessions: TestSession[] = sampleTopics.slice(0, 6).map((topic, index) => ({
  id: `session-${index + 1}`,
  user_id: DEMO_USER_ID,
  subject_id: topic.subject_id,
  chapter_id: topic.chapter_id,
  topic_id: topic.id,
  started_at: new Date(Date.now() - (index + 1) * 86400000).toISOString(),
  completed_at: new Date(Date.now() - (index + 1) * 86400000 + 2100000).toISOString(),
  answers: [],
  final_score: 58 + index * 5,
  ability_estimate: 50 + index * 4,
  weak_concepts: index % 2 === 0 ? [topic.key_concepts[0].toLowerCase().replace(/[^a-z0-9]+/g, '_')] : [],
  strong_concepts: [topic.key_concepts[0].toLowerCase().replace(/[^a-z0-9]+/g, '_')],
  status: 'completed',
}));
